### ISSUE TITLE
Return value of Orchid\Press\Entities\Single::locale() must be of the type array, null returned

### ISSUE THREAD

**Issue by gabeaventh** [orchidsoftware/platform#748] opened 2018-12-18 06:51 UTC
### Expected Behavior
Show Demo Page

### Actual Behavior
it shows this Error-> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Return value of Orchid\Press\Entities\Single::locale() must be of the type array, null returned

### Steps to Reproduce the Problem

  1.Enter Dashboard
  2.Press Demo Page menu
  3.it shows "Return value of Orchid\Press\Entities\Single::locale() must be of the type array, null returned"

### Specifications

  - ORCHID Version: 3.1.7
  - Laravel Version: 5.7.18
  - PHP Version: 7.1++
  - Database Version: 5.7

### Other Notes
my screenshot

<img width="1226" alt="screen shot 2018-12-18 at 13 41 57" src="https://user-images.githubusercontent.com/7519522/50136547-b97ae880-02ca-11e9-9037-b8b513205a48.png">

**Comment by gabeaventh** [comment] 2018-12-18 06:57
Update dashboard/press/posts/demo/create is showing the same behavior as demo-page

**Comment by tabuna** [comment] 2018-12-18 06:58
Plz run “artisan vendor:publish” and chuse PressServiceProvider

**Comment by gabeaventh** [comment] 2018-12-18 06:59
i already run veondor:publish -> 0 which is publishing all

**Comment by tabuna** [comment] 2018-12-18 07:37
The problem is that you have not published the configuration file [`press.php`]( https://github.com/orchidsoftware/platform/blob/master/config/press.php)

**Comment by gabeaventh** [comment] 2018-12-18 08:32
i reinstall the orchid on another fresh installation of laravel, and its working fine, but model seems not picking up any of the models after finished creating model using model buldozer, but it created the ModelName.php

**Comment by tabuna** [comment] 2018-12-18 08:35
I am glad that the problem was successfully solved.
The bulldozer only creates models and their migrations, and also allows you to specify connections (effective when there are a lot of them).

So far, he still does not know how to work with already created models.

**Comment by gabeaventh** [comment] 2018-12-18 08:55
but it supposed to show the models in buldozer/Model Builder right?

but it doesnt show my models

**Comment by tabuna** [comment] 2018-12-18 09:11
I will close this because the problem is solved.

> but it supposed to show the models in buldozer/Model Builder right?


It does not show already existing models.

If you describe how it works, it will look something like this:

1. You create a model through the graphic interface and specify their fields.
2. Establish a relationship between them
3. Click to build everything.

Physical migration files and models will be created.

**Closed by tabuna** 2018-12-18 09:11 UTC
