### ISSUE TITLE
Listener layout not updating with RadioButtons or Checkbox

### ISSUE THREAD

**Issue by TiagoDamascena** [orchidsoftware/platform#1090] opened 2020-05-11 09:44 UTC
**Describe the bug**
Listener layout not trigger on RadioButtons and Checkbox fields.

**To Reproduce**

  1. Create a Screen with a RadioButton or Checkbox
  2. Create a Listener layout with target on this field
  3. Change field value

**Expected behavior**
Form change according to Listener layout

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Chrome
 - Version 81

**Server (please complete the following information):**
  - Platfrom Version: 7.2.3
  - Laravel Version: 7.10.1
  - PHP Version:  7.3.9
  - Database:  MySql
  - Database Version:  8.0.17

**Additional context**

**Comment by tabuna** [comment] 2020-05-11 12:05
Hey @TiagoDamascena . Thank you for paying attention and writing.

Yes, I confirm there is such a problem when there are several checkboxes or radio with the same names on the screen.

![screencast-localhost_8000-2020 05 11-15_01_45](https://user-images.githubusercontent.com/5102591/81559688-8857f800-9398-11ea-8496-e7b397da91c0.gif)

I have already found a way to fix this behavior and it will be fixed soon.

**Closed** 2020-05-11 13:21 UTC
Labels: Errors

**Comment by tabuna** [comment] 2020-05-11 13:23
The [release](https://github.com/orchidsoftware/platform/releases/tag/7.2.6) of a patch is already out.
Do not hesitate to open it or any other issue again

**Comment by TiagoDamascena** [comment] 2020-05-13 17:26
Checkbox is working well but radio button is only working when selected from keyboard, if i select clicking it don't change the layout.

**Comment by tabuna** [comment] 2020-05-13 18:51
Hmm,  @TiagoDamascena can you tell me more?
I am using the following code:

```php
<?php

declare(strict_types=1);

namespace App\Orchid\Screens;

use App\Orchid\Layouts\RadioListener;
use Orchid\Screen\Fields\Radio;
use Orchid\Screen\Layout;
use Orchid\Screen\Screen;

class PlatformScreen extends Screen
{
    /**
     * Display header name.
     *
     * @var string
     */
    public $name = 'Dashboard';

    /**
     * Display header description.
     *
     * @var string
     */
    public $description = 'Welcome';

    /**
     * Query data.
     *
     * @return array
     */
    public function query(): array
    {
        return [];
    }

    /**
     * Button commands.
     *
     * @return Action[]
     */
    public function commandBar(): array
    {
        return [];
    }


    public function asyncRadio(string $radio = null)
    {
        return [
            'radioResult' => $radio,
        ];
    }

    /**
     * Views.
     *
     * @return Layout[]
     */
    public function layout(): array
    {
        return [

            Layout::rows([
               Radio::make('listener')
                   ->placeholder('Radio 1')
                   ->value('foo'),

               Radio::make('listener')
                  ->placeholder('Radio 2')
                  ->value('bar')
            ]),

            RadioListener::class,
        ];
    }
}

```

and layouts:

```php
<?php

namespace App\Orchid\Layouts;

use Orchid\Screen\Fields\Input;
use Orchid\Screen\Layout;
use Orchid\Screen\Layouts\Listener;

class RadioListener extends Listener
{
    /**
     * List of field names for which values will be listened.
     *
     * @var string[]
     */
    protected $targets = [
        'listener',
    ];

    /**
     * What screen method should be called
     * as a source for an asynchronous request.
     *
     * The name of the method must
     * begin with the prefix "async"
     *
     * @var string
     */
    protected $asyncMethod = 'asyncRadio';

    /**
     * @return Layout[]
     */
    protected function layouts(): array
    {
        return [
            Layout::rows([
                Input::make('radioResult')
                    ->readonly(),
            ]),
        ];
    }
}

```

**Comment by TiagoDamascena** [comment] 2020-05-13 19:22
I'm using the RadioButtons field with two options, like this:

```
RadioButtons::make('course.presential')
                ->options([
                    1 => 'Sim',
                    0 => 'Não'
                ])
                ->value(0)
                ->title('Curso presencial?'),
```

**Comment by tabuna** [comment] 2020-05-13 20:29
@TiagoDamascena Yes, I reproduced this problem.
It appeared due to the fact that there is no trigger because we actually click on the button and not on the checkbox. Looks like we just need to add a call trigger

```js
// resources/js/controllers/fields/radiobutton_controller.js

import { Controller } from 'stimulus';

export default class extends Controller {
    /**
     *
     */
    checked(event) {
        event.target.offsetParent.querySelectorAll('input').forEach((input) => {
            input.removeAttribute('checked');
        });

        event.target.setAttribute('checked', 'checked');
        event.target.dispatchEvent(new Event("change"));
    }
}

```

**Comment by tabuna** [comment] 2020-05-13 20:47
I added this to the release 7.2.7 
Please check again.

**Comment by TiagoDamascena** [comment] 2020-05-13 21:31
It's working now, thanks for your attention and your great work.
