### ISSUE TITLE
Duplicated Quill toolbar

### ISSUE THREAD

**Issue by mwkcoding** [orchidsoftware/platform#1053] opened 2020-03-01 18:59 UTC
**Describe the bug**
Two identical Quill toolbars showing up when using the Quill field in a layout.

**To Reproduce**

  1. Install Orchid
  1. Follow guide to make Email Sender Layout (https://orchid.software/en/docs/quickstart/)
  1. Visit page and see the duplicated Quill toolbar

**Expected behavior**
Not seeing two Quill toolbars?

**Screenshots**
![image](https://user-images.githubusercontent.com/16936030/75631808-5555f300-5bf6-11ea-9871-9074dec551a9.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.3
 - Browser: Chrome Version 80.0.3987.116
 - Version: ???

**Server (please complete the following information):**
  - Platform Version: 6.10.2
  - Laravel Version: 6.14
  - PHP Version:  7.4.3
  - Database:  MySQL
  - Database Version: 5.7

**Additional context**

**Comment by tabuna** [comment] 2020-03-01 20:00
Hi @mwkcoding 

Do you have any errors in the browser console?
On the screen with a list of fields, is this reproduced?

**Comment by mwkcoding** [comment] 2020-03-02 14:50
I have the following errors in my browser console:
![image](https://user-images.githubusercontent.com/16936030/75687090-8f2e0480-5c9d-11ea-9d6a-1c7e3c49e705.png)

**Comment by mwkcoding** [comment] 2020-03-02 14:53
It might be worth noting that this happened after an update of orchid with `composer update`. I don't remember from or to which version it was though

**Comment by tabuna** [comment] 2020-03-02 14:54
@mwkcoding  I think it’s now clear why duplication occurs. Please correct error 502, this is due to your web server or tunnel/proxy settings

**Comment by mwkcoding** [comment] 2020-03-02 15:23
@tabuna How do I correct an error I didn't make? I'm using Laravel Valet on MacOS. And like I wrote, this happened after an update.

**Comment by tabuna** [comment] 2020-03-02 15:24
502 error is a web server error, can we see the logs?
And a detailed answer in the browser network tab?

**Comment by mwkcoding** [comment] 2020-03-02 15:26
The error disappeared by itself after I reloaded the page with the devtools open (ignores cache) and I now have this error
![image](https://user-images.githubusercontent.com/16936030/75690070-8b50b100-5ca2-11ea-989c-58d1da093e2f.png)

**Comment by tabuna** [comment] 2020-03-02 15:31
> The error disappeared by itself after I reloaded the page with the devtools open (ignores cache) and I now have this error

Notifications are polled every few minutes. Therefore, that error is no longer there.
Hmm, please check in incognito mode with browser extensions disabled.

**Comment by mwkcoding** [comment] 2020-03-02 21:35
Incognito has same result.

**Comment by mwkcoding** [comment] 2020-03-04 15:51
@tabuna Any idea what I can do to fix this?

**Comment by mwkcoding** [comment] 2020-03-04 16:07
It seems to have disappeared after I updated and ran `php artisan cache:clear && php artisan config:cache`

**Comment by tabuna** [comment] 2020-03-04 16:13
> Any idea what I can do to fix this?

How about a little research? (Better to do it in a new project.)

You can publish all js/css files to your applications and compile them yourself.
To do this, run: 

1. `artisan preset orchid-source`
2. `npm install`
3. `npm run dev`

All files are published to your application and you can analyze why you are accessing the element returns null.

**Comment by tabuna** [comment] 2020-04-11 20:21
I will close this issue.
If you are still experiencing such a problem, please feel free to open it again.

**Closed by tabuna** 2020-04-11 20:21 UTC
Labels: Errors, Pending

**Comment by TimeTravel-1** [comment] 2020-08-01 10:16
I encounter duplication when the back button is pressed

**Comment by ecuation** [comment] 2021-02-02 11:04
Same error here, it happens when navigating from pages.

**Comment by blankster** [comment] 2021-02-02 11:52
@ecuation did you tried the above? If yes, how can it be reproduced?

**Comment by ysdis** [comment] 2022-04-22 18:37
Same behavior but the toolbar in my case duplicates when validation errors happens and controller returns back to form:
![image](https://user-images.githubusercontent.com/48926547/164774396-12d88a28-7761-4a7c-95a7-be1a1604096e.png)

**Comment by e1sep0** [comment] 2023-08-08 12:29
The same behavior in modal, when i try to create new instance
![image](https://github.com/orchidsoftware/platform/assets/5094299/0a37b225-a895-4030-b1d6-d83ecba73a40)

When trying to edit some model, behavior is correct:
![image](https://github.com/orchidsoftware/platform/assets/5094299/7ab435fa-064d-4fb0-abb3-7be2a9fcec6e)

**Comment by qvarts** [comment] 2024-02-08 10:37
The same behavior when Turbo cache = true and using browser history navigation buttons.

Steps to reproduce the behavior:

1 Install Orchid
2 Set turbo cache = true in config/platform.php
2 Visit Examples->Form Elements->Text Editors page
3 Go to any other page and go back with the browser history navigation button or Alt + Arrow Left

You will see two SimpleMDE editor and two Quill toolbars like in screenshot:

![Firefox_Screenshot_2024-02-08T10-00-35 027Z](https://github.com/orchidsoftware/platform/assets/98330685/8411cb13-e05c-4a01-9519-f53a14c486b6)

**Comment by JayJCodez** [comment] 2024-08-19 17:40
The issue most of you are having is due to re-renders. You can keep track of the state of your editor and make sure it renders only once. 

Solution:

Initialization Check: Added a check to ensure that Quill is initialized only once. This prevents multiple instances of Quill from being created and thus prevents the toolbar from loading multiple times.

Content Update Check: Adjusted the componentDidUpdate method to only update the content if editorState has changed, without initialising Quill.

Example: 

```
import React, { Component, createRef } from "react";
import Quill from "quill";
![Screenshot 2024-08-19 at 18 39 43](https://github.com/user-attachments/assets/cfa076e4-f5bd-48dc-926f-c0cddcc4585d)
![Screenshot 2024-08-19 at 18 39 57](https://github.com/user-attachments/assets/9c3b2b24-def0-45d6-9a5d-d6d89698268e)

import "quill/dist/quill.snow.css";

interface MyEditorProps {
  editorState: string;
  onChange: (newContent: string) => void;
}

class MyEditor extends Component<MyEditorProps> {
  private editorRef = createRef<HTMLDivElement>();
  private quill?: Quill;  // Use optional chaining for Quill instance

  componentDidMount() {
    this.initializeQuill(); // Initialize Quill when the component mounts
  }

  componentDidUpdate(prevProps: MyEditorProps) {
    // Only update the content if editorState has changed
    if (prevProps.editorState !== this.props.editorState && this.quill) {
      this.quill.root.innerHTML = this.props.editorState;
    }
  }

  initializeQuill() {
    if (this.editorRef.current && !this.quill) {
      // Initialize Quill only if it has not been initialized
      this.quill = new Quill(this.editorRef.current, {
        theme: "snow",
        modules: {
          toolbar: [
            [{ header: "1" }, { header: "2" }],
            [{ list: "ordered" }, { list: "bullet" }],
            ["bold", "italic", "underline"],
            [{ align: [] }],
            ["link"],
          ],
        },
      });

      // Set up the event listener for text changes
      this.quill.on("text-change", () => {
        if (this.quill) {
          this.props.onChange(this.quill.root.innerHTML);
        }
      });

      // Set initial content
      if (this.props.editorState) {
        this.quill.root.innerHTML = this.props.editorState;
      }
    }
  }

  render() {
    return (
      <div>
        <div ref={this.editorRef} style={{ minHeight: "200px" }}></div>
      </div>
    );
  }
}

export default MyEditor;

```
